### ISSUE TITLE
Levantar el sistema

### ISSUE THREAD

**Issue by wellynton1** [orijmm/proyecto_2#1]
Buenas tardes, he cumplido los requrimientos en la instalacion y llego hasta el login, pero me sucede esto:
![image](https://user-images.githubusercontent.com/33947690/43032247-1231794a-8c78-11e8-8da9-82019489c254.png)

Whoops, looks like something went wrong.
1/1
FatalErrorException in Role.php line 9:
Declaration of App\Support\Authorization\AuthorizationRoleTrait::detachPermissions($permissions) must be compatible with Zizaco\Entrust\EntrustRole::detachPermissions($permissions = NULL)
in Role.php line 9

**Comment by orijmm** [comment]
el usuario admin es : admin y su contraseña: secret

Si forzaste la contraseña capaz ese sea el error.
Corre: php artisan migrate:refresh --seed
Eso para borrar las tablas y volverlas a crear con los datos del seeder.

Avisa si sigue dando error.

**Comment by wellynton1** [comment]
Estimada Oriana.

Excelente, tenias razón force el pass y paso eso,  muy bueno tu trabajo y consultarte el odontograma aun esta en avanze cierto?

Gracias.

**Comment by wellynton1** [comment]
Entiendo, sin embargo no aplica ni guarda las opciones que se le aplican a las dentaduras en el odontograma, o algo no instalé en los CSS?

**Comment by orijmm** [comment]
Hola buenos dias, subi un par de cambios debería arreglar el problema.

Igual verifica con f12 cualquier error de javascript

**Comment by wellynton1** [comment]
Estimada Oriana.

Todo bién muchas gracias, ahora mi consulta si deseo quitar un estado de una dentadura en el odontograma, que se modificaria?

Gracias.

**Comment by orijmm** [comment]
Hola. Faltaría editar eso.

Saludos

**Comment by wellynton1** [comment]
Estimada Oriana.

Estos días, eh intentado quitar el estado de una dentadura en el odontograma, pero no avanzo mucho, espero tu apoyo gracas.

**Comment by wellynton1** [comment]
Otra consulta.

Si deseo cambiar en el dashboard los ultimos pacientes en lugar de usuarios que me recomiendas. Gracias.

**Comment by freddyaq27** [comment]
> 
> 
> Buenas tardes, he cumplido los requrimientos en la instalacion y llego hasta el login, pero me sucede esto:
> ![image](https://user-images.githubusercontent.com/33947690/43032247-1231794a-8c78-11e8-8da9-82019489c254.png)
> 
> Whoops, looks like something went wrong.
> 1/1
> FatalErrorException in Role.php line 9:
> Declaration of App\Support\Authorization\AuthorizationRoleTrait::detachPermissions($permissions) must be compatible with Zizaco\Entrust\EntrustRole::detachPermissions($permissions = NULL)
> in Role.php line 9

Hola, cuales son los requisitos que tengo que instalar para que funcione el sistema?
Gracias de antemano

**Comment by orijmm** [comment]
> > Buenas tardes, he cumplido los requrimientos en la instalacion y llego hasta el login, pero me sucede esto:
> > ![image](https://user-images.githubusercontent.com/33947690/43032247-1231794a-8c78-11e8-8da9-82019489c254.png)
> > Whoops, looks like something went wrong.
> > 1/1
> > FatalErrorException in Role.php line 9:
> > Declaration of App\Support\Authorization\AuthorizationRoleTrait::detachPermissions($permissions) must be compatible with Zizaco\Entrust\EntrustRole::detachPermissions($permissions = NULL)
> > in Role.php line 9
> 
> Hola, cuales son los requisitos que tengo que instalar para que funcione el sistema?
> Gracias de antemano

Al parecer no corriste los seeders

**Comment by melchorituarte** [comment]
Buen dia,
hmmm yo ni siquiera llego al login, me sale este error:
[Fri Feb 22 12:44:00 2019] PHP Fatal error:  Unknown: Failed opening required 'C:\xampp\dental_sys-master/server.php' (include_path='C:\xampp\php\PEAR') in Unknown on line 0
